import { Globe, Layout, Cpu, Wrench, BarChart3, ClipboardList, Lightbulb, Settings } from 'lucide-react';

export default {
    home: {
        badge: 'Available for new projects',
        heroH1: (
            <>
                I turn complex workflows into{' '}
                <span className="gradient-text">clean web apps</span> — so you
                can focus on growing your business.
            </>
        ),
        heroDesc:
            'Full-stack developer specializing in React & Laravel. I design, build, and ship custom web applications — from first wireframe to production deployment.',
        trustMicro:
            'Passionate about creating modern, robust web applications and always eager to take on new challenges.',
        ctaPrimary: "Let's Talk",
        ctaSecondary: 'Download CV',
        trustBar: [
            // { number: '4+', label: 'Delivered Apps' },
            { number: '1.5+', label: 'Years Freelance Experience' },
            { number: '2', label: 'Personal Projects' },
            { number: '< 24h', label: 'Avg. Response Time' },
        ],
        servicesLabel: 'Services',
        servicesTitle: 'What I Offer',
        servicesSubtitle: 'I build modern websites and web applications that help businesses grow, manage their work, and turn ideas into real products.',
        services: [
            {
                icon: <Globe size={26} />,
                title: 'Websites & Online Presence',
                desc: 'Portfolio websites, company sites, and landing pages — modern, responsive, and ready to impress.',
            },
            {
                icon: <Cpu size={26} />,
                title: 'Custom Web Applications',
                desc: 'Tailored apps with dashboards, user accounts, and custom features built around your needs.',
            },
            {
                icon: <BarChart3 size={26} />,
                title: 'Management & Business Systems',
                desc: 'Inventory tracking, registration systems, and internal tools to organize your operations.',
            },
        ],
        viewAllServices: 'View All Services',
        productLabel: 'Product',
        productTitle: 'Registration App',
        productHeading: 'Get up and running in 48 hours',
        productDesc:
            'A ready-made registration system for events, political parties, organizations, and any group that needs to manage members, sign-ups, and outreach efficiently.',
        productFeatures: [
            'Event Registration',
            'Bulk Import',
            'Attendee Management',
            'CSV Export',
            'Roles & Permissions',
            'Consent Tracking',
        ],
        productCta: 'See Demo',
        productCtaSecondary: 'Request Customization',
        portfolioLabel: 'Portfolio',
        portfolioTitle: 'Featured Projects',
        portfolioSubtitle: 'Real-world applications delivering measurable business outcomes.',
        viewCaseStudies: 'View All Case Studies',
        ctaHeading: 'Ready to simplify your operations?',
        ctaDesc: "Let's talk about your project. Reach out to get a clear roadmap within 24 hours.",
        ctaBtn: "Let's Talk",
        ctaServices: 'View Services',
        projects: [
            {
                title: 'On-demand Registration App',
                category: 'Management System',
                desc: 'A configurable registration system for any organization with multi-step signups and role-based access.',
                thumb: '/img/reg1.PNG',
            },
        ],
    },
    services: {
        heroTitle: 'What I Offer',
        heroSubtitle: 'I build modern websites and web applications that help businesses grow, manage their work, and turn ideas into real products.',
        offeringsLabel: 'Services',
        offerings: [
            {
                icon: <Layout size={26} />,
                title: 'Portfolio Websites',
                desc: 'Clean, modern websites to showcase your work and personal brand.',
            },
            {
                icon: <Globe size={26} />,
                title: 'Business Websites',
                desc: 'Professional websites that build trust and present your company online.',
            },
            {
                icon: <Cpu size={26} />,
                title: 'Custom Web Apps',
                desc: 'Tailored applications with dashboards, user accounts, and custom features.',
            },
            {
                icon: <Settings size={26} />,
                title: 'Management Systems',
                desc: 'Tools to organize operations, teams, and daily workflows in one place.',
            },
            {
                icon: <BarChart3 size={26} />,
                title: 'Inventory Systems',
                desc: 'Track stock, products, and sales with simple, efficient systems.',
            },
            {
                icon: <ClipboardList size={26} />,
                title: 'Registration Systems',
                desc: 'Online forms and systems to collect and manage user data with ease.',
            },
            {
                icon: <Lightbulb size={26} />,
                title: 'Idea to Web App',
                desc: 'Transform your idea into a fully functional web application.',
            },
            {
                icon: <Wrench size={26} />,
                title: 'Maintenance & Support',
                desc: 'Ongoing improvements, bug fixes, and performance optimization.',
            },
        ],
        techStack: 'Technologies: React, Laravel, APIs',
        processLabel: 'Process',
        processTitle: 'How I Work',
        processSubtitle: 'A simple, structured approach to delivering quality work on time.',
        process: [
            { num: '01', title: 'Discovery', desc: 'We discuss your needs, goals, and timeline. I map your workflow and identify requirements.' },
            { num: '02', title: 'Proposal', desc: 'You get a clear scope, timeline, and fixed quote. No surprises.' },
            { num: '03', title: 'Build', desc: 'I develop your app with regular updates and preview links. You see progress weekly.' },
            { num: '04', title: 'Launch', desc: 'We deploy, test, and train your team. Post-launch support included.' },
        ],
        faqLabel: 'FAQ',
        faqTitle: 'Common Questions',
        faqs: [
            { q: 'Do you charge hourly or fixed?', a: 'I prefer fixed-price for defined scopes. For ongoing work or retainers, I offer monthly rates.' },
            { q: 'What if I need changes after launch?', a: 'All projects include a revision period. After that, I offer monthly maintenance plans to keep things running smoothly.' },
            { q: 'How long does a typical project take?', a: 'A simple website can be ready in 1–2 weeks. Custom web applications typically take 4–8 weeks depending on complexity.' },
            { q: 'Do you offer ongoing support?', a: 'Yes. I offer flexible monthly support plans for bug fixes, updates, new features, and performance improvements.' },
        ],
        ctaHeading: 'Have a project in mind?',
        ctaDesc: "Let's discuss your goals. Reach out and I'll send you a clear roadmap within 24 hours.",
        ctaBtn: "Let's Talk",
    },
    work: {
        heroTitle: 'Work & Case Studies',
        heroSubtitle: "Real-world applications I've built, the challenges solved, and the outcomes delivered.",
        labels: {
            role: 'Role',
            stack: 'Stack',
            timeline: 'Timeline',
            problem: 'Problem',
            approach: 'Approach',
            solution: 'Solution',
            impact: 'Impact',
            keyLearnings: 'Key Learnings',
        },
        caseStudies: [
            // {
            //     category: 'Enterprise',
            //     title: 'Order & Mission Management System',
            //     oneLiner: 'Simplified operations for a field sales team.',
            //     role: 'Lead Developer',
            //     tech: 'React + Laravel',
            //     timeline: '8 weeks',
            //     images: [
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.25.jpeg',
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.24.jpeg',
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.24 (1).jpeg',
            //     ],
            //     problem: 'The client tracked missions and orders with spreadsheets and paper — coordination errors, missed deliveries, and slow billing.',
            //     approach: 'Discovery with operations team, mapped current workflow, prototyped a web app focused on quick order entry and dispatch. Prioritized mobile-friendly forms for drivers.',
            //     solution: 'Web app with order intake, mission assignment, real-time status, PDF invoicing, and CSV export for accounting. Included role-based access for dispatchers and drivers.',
            //     impact: 'Replaced manual processes; reduced order assignment time and errors. Operations manager reported smoother day-to-day runs.',
            //     learning: 'Start with core workflow first; mobile usability for field workers is essential.',
            //     tags: ['React', 'Laravel', 'MySQL', 'REST API', 'PDF Export'],
            // },
            // {
            //     category: 'SaaS',
            //     title: 'Childcare Center Platform',
            //     oneLiner: 'From intake to monthly billing, all in one app.',
            //     role: 'Full-stack Developer',
            //     tech: 'React + Laravel',
            //     timeline: '6 weeks',
            //     images: [
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.26.jpeg',
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.23 (3).jpeg',
            //     ],
            //     problem: 'Paper forms, manual enrollment, and separate spreadsheets for payments created administrative overhead and parent confusion.',
            //     approach: 'Built a parent-facing registration flow, admin dashboard for enrollments, and automated monthly billing with receipts.',
            //     solution: 'Online registration with file upload, parent portal, invoicing, and automatic monthly reminders. Admins can export attendance & billing.',
            //     impact: 'Simplified onboarding and payments; staff reported fewer no-shows and cleaner accounting.',
            //     learning: 'Consent & privacy handling up front saves headaches. Make parent UX simple — one form with a progress indicator.',
            //     tags: ['React', 'Laravel', 'Stripe', 'PostgreSQL', 'Email Automation'],
            // },
            // {
            //     category: 'Government',
            //     title: 'Political Party Registration System',
            //     oneLiner: 'Secure voter/member registration for a political campaign.',
            //     role: 'Lead Developer',
            //     tech: 'React + Laravel',
            //     timeline: '5 weeks',
            //     images: [
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.22 (1).jpeg',
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.22 (2).jpeg',
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.22 (3).jpeg',
            //     ],
            //     problem: 'The party needed a scalable, secure way to collect membership info, handle event sign-ups, and generate lists for outreach. Paper sign-ups were error-prone and slow.',
            //     approach: 'Designed audit-friendly forms, opt-in management, and secure export pipelines. Delivered training to ensure proper data stewardship.',
            //     solution: 'A registration portal with validation, administrative lists, CSV export, and permissioned access for regional admins. Built-in consent tracking.',
            //     impact: 'Faster member acquisition and better-targeted outreach. Team could act on sign-ups within hours instead of days.',
            //     learning: 'Security, consent, and auditing are non-negotiable for political projects. Provide clear admin controls.',
            //     tags: ['React', 'Laravel', 'MySQL', 'Role-Based Access', 'CSV Export'],
            // },
            // {
            //     category: 'Corporate',
            //     title: 'Company Information Website',
            //     oneLiner: 'Professional web presence for a growing business.',
            //     role: 'Web Developer',
            //     tech: 'React',
            //     timeline: '2 weeks',
            //     images: [
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.23.jpeg',
            //         '/img/WhatsApp Image 2026-02-09 at 07.20.23 (1).jpeg',
            //     ],
            //     problem: 'The company had no online presence and relied on word-of-mouth. They needed a professional site to attract new clients.',
            //     approach: 'Designed a clean, responsive site focused on services, testimonials, and clear calls to action.',
            //     solution: 'A modern multi-section website with service pages, contact form, SEO optimization, and responsive design.',
            //     impact: 'Professional online presence that improved client inquiries and brand perception.',
            //     learning: 'Clean design and clear messaging matter more than feature count for business sites.',
            //     tags: ['React', 'CSS', 'Responsive', 'SEO'],
            // },
            {
                category: 'Management System',
                title: 'On-demand Registration App',
                oneLiner: 'A custom-built registration platform for organizations with specific workflow needs.',
                images: [
                    '/img/reg1.PNG',
                    '/img/reg2.PNG',
                    '/img/reg2.0.PNG',
                    '/img/reg2.1PNG.PNG',
                    '/img/reg3.PNG',
                    '/img/reg3.1.PNG',
                    '/img/reg4.PNG',
                    '/img/reg5.PNG',
                    '/img/reg6.PNG',
                    '/img/reg7.PNG',
                ],
                problem: 'Organizations like political parties, NGOs, and associations needed a scalable digital registration system to replace paper sign-ups. Many needed a solution that could be quickly launched and customized for their specific local requirements without the high cost of from-scratch development.',
                approach: 'Built a flexible architecture where a single codebase can be rapidly configured for different organizations. Developed a multi-step signup form with NIN validation and a role-based admin panel with tiered permissions.',
                solution: 'A fully configurable platform with public registration (4-step form with identity verification), referral system with personal tokens, admin dashboard for member management, flexible branding settings (logo, colors, hero text), geographic data hierarchy (Wilayas/Communes), and bilingual Arabic/English support with RTL.',
                impact: 'Designed to handle thousands of members and multi-regional data structures. The system drastically reduces manual registration time through automation and enables real-time member approval and regional delegation for large-scale organizations.',
                learning: 'Flexible system architecture pays off when you plan for modularity from day one. Multi-step forms with validation at each step drastically reduce drop-off rates.',
                tags: ['React', 'Laravel', 'MySQL', 'Customizable', 'Role-Based Access', 'RTL Support', 'Ant Design', 'Multi-Step Forms'],
            },
        ],
        ctaHeading: 'Want a similar solution?',
        ctaDesc: "Let's discuss how I can help your organization with a custom or off-the-shelf solution.",
        ctaBtn: "Let's Talk",
        ctaBtnSecondary: 'See Product Demo',
    },
    about: {
        heroName: 'Merabet Ayache Zakaria',
        heroP1: 'I build modern websites and web applications that help businesses present themselves clearly, manage their work more efficiently, and turn ideas into digital products. My focus is on creating clean, practical, and user-friendly solutions for portfolios, company websites, management systems, registration platforms, and custom web apps.',
        heroP2: 'I work with React and Laravel, with an emphasis on usability, reliability, and solutions that create real value.',
        ctaBtn: 'Work With Me',
        cvBtn: 'Download CV',
        skillsLabel: 'Tech & Tools',
        skillsTitle: 'What I Work With',
        skillsSubtitle: 'The core technologies I use to deliver quality web applications.',
        skills: [
            {
                group: 'Frontend',
                items: ['HTML', 'CSS', 'JS', 'React', 'Antd', 'Responsive Design'],
            },
            {
                group: 'Backend',
                items: ['Laravel', 'MySQL', 'REST APIs', 'ORM', 'Authentication'],
            },
            {
                group: 'Tools',
                items: ['Git', 'GitHub', 'Axios'],
            },
            {
                group: 'Data Handling',
                items: ['CSV/PDF Export', 'Import'],
            },
        ],
        ctaHeading: "Let's build something together",
        ctaDesc: "Whether you need a product setup or a fully custom solution, I'm here to help.",
        ctaActionBtn: "Let's Talk"
    },
    contact: {
        label: 'Contact',
        heading: (
            <>
                Let's Build Something <span className="gradient-text">Together</span>
            </>
        ),
        desc: " Just pick your preferred way to reach me and let's talk about your project.",
        channels: {
            whatsapp: 'WhatsApp',
            whatsappDesc: 'Fastest way to reach me. Usually reply within a short time.',
            whatsappCta: 'Message on WhatsApp',
            phone: 'Phone',
            phoneDesc: 'I am available for calls .',
            phoneCta: 'Call Now',
            email: 'Email',
            emailDesc: 'For detailed project briefs or formal inquiries.',
            emailCta: 'Send an Email'
        },
        meta: {
            responseTime: 'Response Time',
            responseTimeVal: 'Within 24 hours',
            availability: 'Availability',
            availabilityVal: 'Remote · Worldwide'
        },
        form: {
            title: 'Send a Message',
            subtitle: 'Fill out the form below and I\'ll get back to you as soon as possible.',
            name: 'Full Name',
            namePlaceholder: 'John Doe',
            email: 'Email Address',
            emailPlaceholder: 'john@example.com',
            phone: 'Phone Number',
            phonePlaceholder: '+213 6XX XXX XXX',
            subject: 'Subject',
            subjectPlaceholder: 'Project inquiry',
            message: 'Message',
            messagePlaceholder: 'Tell me about your project, goals, and timeline...',
            send: 'Send Message',
            sending: 'Sending...',
            successTitle: 'Message Sent!',
            successDesc: 'Thank you for reaching out. I\'ll get back to you within 24 hours.',
            sendAnother: 'Send Another Message',
            errorTitle: 'Something went wrong',
            errorDesc: 'Please try again or reach out via one of the channels above.',
            retry: 'Try Again',
            validationRequired: 'This field is required',
            validationEmail: 'Please enter a valid email address',
            optional: 'Optional',
        }
    },
    footer: {
        brandDesc: 'Full-stack web developer. I design and build modern, custom websites and web applications that help businesses and individuals simplify their workflows and achieve their goals.',
        col1Title: 'Pages',
        col2Title: 'Services',
        col3Title: 'Connect',
        links: {
            services: 'Services',
            products: 'Products',
            work: 'Work',
            about: 'About',
            businessSites: 'Business Websites',
            webApps: 'Custom Web Apps',
            managementSystems: 'Management Systems',
            custom: 'Get a Quote',
            email: 'Email Me',
            downloadCv: 'Download CV'
        },
        rights: 'All rights reserved.'
    }
};
