import { Globe, Layout, Cpu, Wrench, BarChart3, ClipboardList, Lightbulb, Settings } from 'lucide-react';

export default {
    home: {
        badge: 'Available for new projects',
        heroH1: (
            <>
                I turn complex workflows into{' '}
                <span className="gradient-text">clean web apps</span> — so you
                can focus on growing your business.
            </>
        ),
        heroDesc:
            'Full-stack developer specializing in React & Laravel. I design, build, and ship custom web applications — from first wireframe to production deployment.',
        trustMicro:
            'Passionate about creating modern, robust web applications and always eager to take on new challenges.',
        ctaPrimary: "Let's Talk",
        ctaSecondary: 'Download CV',
        trustBar: [
            // { number: '4+', label: 'Delivered Apps' },
            { number: '1.5+', label: 'Years Freelance Experience' },
            { number: '2', label: 'Personal Projects' },
            { number: '< 24h', label: 'Avg. Response Time' },
        ],
        servicesLabel: 'Services',
        servicesTitle: 'What I Offer',
        servicesSubtitle: 'I build modern websites and web applications that help businesses grow, manage their work, and turn ideas into real products.',
        services: [
            {
                icon: <Globe size={26} />,
                title: 'Websites & Online Presence',
                desc: 'Portfolio websites, company sites, and landing pages — modern, responsive, and ready to impress.',
            },
            {
                icon: <Cpu size={26} />,
                title: 'Custom Web Applications',
                desc: 'Tailored apps with dashboards, user accounts, and custom features built around your needs.',
            },
            {
                icon: <BarChart3 size={26} />,
                title: 'Management & Business Systems',
                desc: 'Inventory tracking, registration systems, and internal tools to organize your operations.',
            },
        ],
        viewAllServices: 'View All Services',
        productLabel: 'Product',
        productTitle: 'Registration App',
        productHeading: 'Get up and running in 48 hours',
        productDesc:
            'A ready-made registration system for events, political parties, organizations, and any group that needs to manage members, sign-ups, and outreach efficiently.',
        productFeatures: [
            'Event Registration',
            'Bulk Import',
            'Attendee Management',
            'CSV Export',
            'Roles & Permissions',
            'Consent Tracking',
        ],
        productCta: 'See Demo',
        productCtaSecondary: 'Request Customization',
        portfolioLabel: 'Portfolio',
        portfolioTitle: 'Featured Projects',
        portfolioSubtitle: 'Real-world applications delivering measurable business outcomes.',
        viewCaseStudies: 'View All Case Studies',
        ctaHeading: 'Ready to simplify your operations?',
        ctaDesc: "Let's talk about your project. Reach out to get a clear roadmap within 24 hours.",
        ctaBtn: "Let's Talk",
        ctaServices: 'View Services',
        projects: [
            {
                title: 'On-demand Registration App',
                category: 'Management System',
                desc: 'A configurable registration system for any organization with multi-step signups and role-based access.',
                thumb: '/img/reg1.PNG',
            },
            {
                title: 'Association Management System',
                category: 'Management Platform',
                desc: 'Centralized multi-role web platform for Algerian associations — managing members, centres, and operations across Wilayas and Communes.',
                thumb: '/img/association/asso_en1.PNG',
            },
        ],
    },
    services: {
        heroTitle: 'What I Offer',
        heroSubtitle: 'I build modern websites and web applications that help businesses grow, manage their work, and turn ideas into real products.',
        offeringsLabel: 'Services',
        offerings: [
            {
                icon: <Layout size={26} />,
                title: 'Portfolio Websites',
                desc: 'Clean, modern websites to showcase your work and personal brand.',
            },
            {
                icon: <Globe size={26} />,
                title: 'Business Websites',
                desc: 'Professional websites that build trust and present your company online.',
            },
            {
                icon: <Cpu size={26} />,
                title: 'Custom Web Apps',
                desc: 'Tailored applications with dashboards, user accounts, and custom features.',
            },
            {
                icon: <Settings size={26} />,
                title: 'Management Systems',
                desc: 'Tools to organize operations, teams, and daily workflows in one place.',
            },
            {
                icon: <BarChart3 size={26} />,
                title: 'Inventory Systems',
                desc: 'Track stock, products, and sales with simple, efficient systems.',
            },
            {
                icon: <ClipboardList size={26} />,
                title: 'Registration Systems',
                desc: 'Online forms and systems to collect and manage user data with ease.',
            },
            {
                icon: <Lightbulb size={26} />,
                title: 'Idea to Web App',
                desc: 'Transform your idea into a fully functional web application.',
            },
            {
                icon: <Wrench size={26} />,
                title: 'Maintenance & Support',
                desc: 'Ongoing improvements, bug fixes, and performance optimization.',
            },
        ],
        techStack: 'Technologies: React, Laravel, APIs',
        processLabel: 'Process',
        processTitle: 'How I Work',
        processSubtitle: 'A simple, structured approach to delivering quality work on time.',
        process: [
            { num: '01', title: 'Discovery', desc: 'We discuss your needs, goals, and timeline. I map your workflow and identify requirements.' },
            { num: '02', title: 'Proposal', desc: 'You get a clear scope, timeline, and fixed quote. No surprises.' },
            { num: '03', title: 'Build', desc: 'I develop your app with regular updates and preview links. You see progress weekly.' },
            { num: '04', title: 'Launch', desc: 'We deploy, test, and train your team. Post-launch support included.' },
        ],
        faqLabel: 'FAQ',
        faqTitle: 'Common Questions',
        faqs: [
            { q: 'Do you charge hourly or fixed?', a: 'I prefer fixed-price for defined scopes. For ongoing work or retainers, I offer monthly rates.' },
            { q: 'What if I need changes after launch?', a: 'All projects include a revision period. After that, I offer monthly maintenance plans to keep things running smoothly.' },
            { q: 'How long does a typical project take?', a: 'A simple website can be ready in 1–2 weeks. Custom web applications typically take 4–8 weeks depending on complexity.' },
            { q: 'Do you offer ongoing support?', a: 'Yes. I offer flexible monthly support plans for bug fixes, updates, new features, and performance improvements.' },
        ],
        ctaHeading: 'Have a project in mind?',
        ctaDesc: "Let's discuss your goals. Reach out and I'll send you a clear roadmap within 24 hours.",
        ctaBtn: "Let's Talk",
    },
    products: {
        heroLabel: 'Real-World Production Case • Open Architecture',
        heroTitle: 'On-Demand Registration System',
        heroSubtitle: 'Enterprise multi-tier digital membership & verification platform built with React 18, Vite 5, Laravel 10 REST API, and MySQL.',
        githubUrl: 'https://github.com/zakariamerabetayache/On-demand-Registration-System',
        githubBtn: 'View on GitHub',
        discussBtn: 'Discuss Architecture',
        metaChips: [
            { label: 'Backend API', value: 'Laravel 10 REST API + MySQL' },
            { label: 'Frontend SPA', value: 'React 18 + Vite 5 + AntD' },
            { label: 'Security & Auth', value: 'Sanctum RBAC + Scoped Queries' },
            { label: 'Project Context', value: 'Client Production -> Open Portfolio' },
        ],
        philosophyLabel: 'Origin & Philosophy',
        philosophyTitle: 'From Client Commission to Production-Grade Open Architecture',
        philosophyQuote: 'Initially commissioned for an organization requiring large-scale digital member onboarding, the contract concluded before full deployment. Rather than shelving the codebase, I re-engineered it into a production-grade, open-architecture portfolio product built in public.\n\nThe system bridges the gap between chaotic paper procedures and modern digital workflows. For me, this project was not just about building features; it was an exercise in mastering Real-World Management Systems: from dissecting core operational problems to designing multi-tier workflows, robust architecture, and frictionless user experiences.',
        problemTitle: 'The Operational Bottlenecks',
        problemDesc: 'Key failure points of traditional membership onboarding:',
        problemItems: [
            { title: 'Paper Sign-ups & Manual Entry', desc: 'Slow, error-prone manual processing of thousands of physical applications, creating administrative backlogs spanning weeks.' },
            { title: 'Identity Fraud & Duplicate Profiles', desc: 'Lack of real-time National ID (NIN) verification allows fraudulent, duplicate, or unverified registrations into member databases.' },
            { title: 'Bespoke Development Overhead', desc: 'Commissioning custom-built portals from scratch for every regional branch or campaign is financially prohibitive.' },
            { title: 'Fragmented Regional Delegation', desc: 'Local and regional branch leaders lack secure, scoped access to view, approve, and export their own member cohorts independently.' },
        ],
        solutionTitle: 'The Architectural Solution',
        solutionDesc: 'A unified white-label platform configured entirely at runtime:',
        solutionItems: [
            { title: 'Guided 4-Step Registration Wizard', desc: 'Progressive disclosure UI enforcing per-step field verification before data progression to maximize user completion rates.' },
            { title: 'Double-Layer NIN Verification', desc: 'Database-level unique constraint paired with pre-flight API validation to definitively eliminate duplicate entries.' },
            { title: 'Runtime White-Label Customization', desc: 'Instant customization of organization logo, primary/secondary color schemes, and terms of service without redeploying.' },
            { title: 'Scoped Multi-Tier RBAC', desc: 'Hierarchical roles (Super Admin, National Admin, Regional Delegate) powered by Laravel Sanctum with automatic geographic query scoping.' },
        ],
        specsLabel: 'Technical Capabilities & Architecture',
        specsTitle: 'Deep Engineering Breakdown',
        specsSubtitle: 'Architected with modern software engineering best practices for scale and security:',
        specs: [
            {
                tag: 'Onboarding UX',
                title: 'Guided 4-Step Multi-Page Wizard',
                desc: 'Progressive disclosure pattern guiding members across 4 distinct phases (Account, Location & Demographics, NIN Validation, Confirmation & Token) with real-time per-step input verification.',
            },
            {
                tag: 'Data Integrity',
                title: 'NIN Anti-Duplicate Verification Engine',
                desc: 'Database unique index on National ID Number plus custom application middleware pre-validation to intercept duplicates before database persistence and deliver clean user feedback.',
            },
            {
                tag: 'Security & RBAC',
                title: 'Tiered RBAC & Jurisdiction Scoping (Sanctum)',
                desc: 'Stateless JWT authentication via Laravel Sanctum. Regional delegate middleware automatically injects assigned Wilaya/Commune IDs into queries, preventing cross-scope data leakage at the controller layer.',
            },
            {
                tag: 'Growth Engine',
                title: 'Viral Referral Engine & Conversion Tracking',
                desc: 'Automated cryptographic token generated per registered member, producing a personalized invite URL (?ref={token}) and powering a real-time top-referrer leaderboard.',
            },
            {
                tag: 'Architecture',
                title: 'Dynamic White-Label Customization Engine',
                desc: 'Organization branding parameters (logo, primary/secondary colors, terms of service) stored in MySQL and injected as CSS custom properties on document root dynamically upon application boot.',
            },
            {
                tag: 'Localization',
                title: 'Bilingual AR/EN & Native RTL Support',
                desc: 'Native Right-to-Left (RTL) layout switching with mirrored UI components, typography optimizations, and full Ant Design ConfigProvider RTL integration.',
            },
            {
                tag: 'Export & Audit',
                title: 'High-Throughput Scoped Data Export',
                desc: 'Direct CSV download streaming via league/csv and PDF summary document rendering via DomPDF, strictly bounded to the requesting administrator authorized jurisdiction.',
            },
            {
                tag: 'Geo Hierarchy',
                title: 'Integrated Geographic Hierarchy (Wilayas & Communes)',
                desc: 'Normalized relational database mapping provinces and districts, powering dynamic cascading dropdowns and regional member segmentation.',
            },
        ],
        screenshotsLabel: 'Visual Walkthrough',
        screenshotsTitle: 'Application Screenshots & Workflow',
        screenshotsSubtitle: 'Click on any screenshot to open the high-resolution lightbox inspector:',
        screenshots: [
            { src: '/img/reg1.PNG', title: 'Step 1: Account & Initial Identity', caption: 'Modern onboarding form with instant email and phone verification' },
            { src: '/img/reg2.0.PNG', title: 'Step 2: Location & Demographic Selection', caption: 'Cascading Wilaya and Commune selection for regional mapping' },
            { src: '/img/reg2.1PNG.PNG', title: 'Step 2.1: National ID (NIN) Verification', caption: 'Automated pre-flight check preventing duplicate registrations' },
            { src: '/img/reg3.PNG', title: 'Step 3: Unique Token & Referral Link', caption: 'Instant cryptographic token and personalized invitation URL' },
            { src: '/img/reg3.1.PNG', title: 'Registration Summary & Submission', caption: 'Complete review of member credentials before final submission' },
            { src: '/img/reg4.PNG', title: 'Admin Suite: Membership Approval Pipeline', caption: 'Hierarchical workflow managing Pending, Approved, and Rejected states' },
            { src: '/img/reg5.PNG', title: 'Admin Suite: Regional Scoping & Filtering', caption: 'Geographically isolated member views and CSV/PDF export tools' },
            { src: '/img/reg6.PNG', title: 'Admin Suite: Dynamic White-Label Settings', caption: 'Runtime logo upload, color palette adjustment, and legal notices' },
        ],
        techStackLabel: 'Engineered With',
        techStackTitle: 'Complete Technology Stack',
        techStackItems: [
            { category: 'Frontend', items: ['React 18', 'Vite 5', 'Tailwind CSS', 'Ant Design', 'Framer Motion', 'Axios'] },
            { category: 'Backend & API', items: ['Laravel 10', 'RESTful Architecture', 'Sanctum JWT', 'Eloquent ORM', 'PHP 8.1+'] },
            { category: 'Database & Security', items: ['MySQL 8', 'Unique Constraints', 'Role-Based Middleware', 'Query Scoping'] },
            { category: 'Export & Utilities', items: ['league/csv (Streaming)', 'DomPDF', 'Git & GitHub', 'RTL Engine'] },
        ],
        ctaTitle: 'Inspect the Source or Discuss Systems Architecture',
        ctaDesc: 'This project is publicly available on GitHub as part of my build-in-public journey. If you need a full-stack engineer who builds scalable, reliable real-world systems, let us connect.',
        ctaGithubBtn: 'View Repository on GitHub',
        ctaContactBtn: 'Get in Touch',
    },
    work: {
        heroTitle: 'Case Studies & Engineering Deep-Dives',
        heroSubtitle: 'A technical breakdown of what I built, why I built it, and how it works under the hood.',
        labels: {
            role: 'Role',
            stack: 'Stack',
            timeline: 'Timeline',
            philosophy: 'Origin & Philosophy',
            problem: 'The Problem',
            solution: 'The Solution',
            techSpec: 'Technical Architecture & Specs',
            techStack: 'Tech Stack',
            viewOnGithub: 'View on GitHub',
        },
        caseStudies: [
            {
                category: 'Enterprise Platform',
                title: 'On-Demand Registration System',
                oneLiner: 'White-label, multi-tenant digital membership & verification platform — built once, configured per organization.',
                role: 'Full-Stack Developer (React 18 + Laravel 10)',
                tech: 'React 18 + Vite 5 + Laravel 10 REST API + MySQL',
                timeline: '~3 months',
                github: 'https://github.com/zakariamerabetayache/On-demand-Registration-System',
                images: [
                    '/img/reg1.PNG',
                    '/img/reg2.PNG',
                    '/img/reg2.0.PNG',
                    '/img/reg2.1PNG.PNG',
                    '/img/reg3.PNG',
                    '/img/reg3.1.PNG',
                    '/img/reg4.PNG',
                    '/img/reg5.PNG',
                    '/img/reg6.PNG',
                    '/img/reg7.PNG',
                ],
                philosophy: "Initially commissioned for a client managing large-scale member registration, the project concluded when the contract ended. Rather than shelving the codebase, I re-engineered it into a production-grade, open-architecture portfolio product built in public. The core engineering philosophy: instead of brittle, hardcoded single-tenant registration forms, build a scalable engine where branding, geographical hierarchy, and access control are pure runtime configurations.",
                problem: "Large organizations (NGOs, political bodies, civic unions) face severe operational bottlenecks: error-prone paper registrations that cannot scale across regions, zero identity validation leading to duplicate and fraudulent accounts, prohibitive costs of building bespoke portals per branch or campaign, and lack of regional delegation tools for local leaders.",
                solution: "A modular, white-label platform where one codebase serves any organization at runtime. Public side: a guided 4-step registration wizard enforcing NIN (National ID Number) uniqueness at both DB and application layers. Each member receives a unique referral token and trackable invite URL. Admin side: a tiered RBAC dashboard powered by Laravel Sanctum for reviewing membership states (Pending / Approved / Rejected), with automated geographical scoping (Wilayas & Communes), instant CSV/PDF export, dynamic runtime branding (logos, colors, ToS), and full bilingual Arabic/English RTL/LTR support.",
                techSpec: [
                    { label: '4-Step Registration Wizard', detail: 'Progressive disclosure form with client and server validation per step, ensuring complete data integrity before step progression.' },
                    { label: 'NIN Anti-Duplicate Verification', detail: 'Database unique index on National ID Number plus application middleware pre-validation to eliminate duplicate entries and return human-readable feedback.' },
                    { label: 'Tiered RBAC & Approval Workflow', detail: 'Powered by Laravel Sanctum. Three hierarchical roles (Super Admin, National Admin, Regional Delegate) managing member lifecycle states (Pending / Approved / Rejected) with scoped database queries.' },
                    { label: 'Viral Referral Engine & Analytics', detail: 'Automated unique token generation creating personalized invitation URLs (?ref={token}), tracking conversion counts and leaderboard rankings.' },
                    { label: 'Dynamic White-Label Branding', detail: 'Settings stored in MySQL and fetched on application boot, dynamically injected as CSS variables for live brand customization without redeploying.' },
                    { label: 'Bilingual AR/EN & Native RTL Support', detail: 'First-class Right-to-Left (RTL) layout switching with mirrored UI elements, custom fonts, and full Ant Design ConfigProvider RTL integration.' },
                    { label: 'Scoped Data Export & Reporting', detail: 'High-throughput CSV streaming via league/csv and PDF generation via DomPDF, strictly bounded to the requesting admin jurisdictional scope.' },
                ],
                tags: ['React 18', 'Vite 5', 'Laravel 10', 'MySQL', 'Sanctum JWT', 'RBAC', 'Multi-Step Form', 'RTL Engine', 'league/csv', 'DomPDF'],
            },
            {
                category: 'Management Platform',
                title: 'Association Management System',
                oneLiner: 'Centralized multi-role web platform for Algerian associations — managing members, centres, and operations across Wilayas and Communes.',
                role: 'Full-Stack Developer (React + Laravel)',
                tech: 'React 18 + Vite + Laravel 10 + MySQL + Sanctum + AntD',
                timeline: '~2.5 months',
                github: 'https://github.com/zakariamerabetayache/association-managment-web-app',
                images: [
                    '/img/association/asso_en1.PNG',
                    '/img/association/asso_en2.PNG',
                    '/img/association/asso_en3.PNG',
                    '/img/association/asso_ar1.PNG',
                    '/img/association/asso_ar2.PNG',
                    '/img/association/asso_ar3.PNG',
                ],
                philosophy: "Non-profit associations and community centres in Algeria typically struggle with manual paperwork and generic tools that fail to match local administrative realities. The philosophy behind this project was to design a purpose-built digital ecosystem natively integrated with Algeria's administrative geography (Wilayas → Communes → Etablissements). It provides clean, role-segregated workflows so every stakeholder — from central administrators to centre managers, associates, and parents — has a dedicated, secure interface in their preferred language.",
                problem: "Community organizations face operational fragmentation: physical paper files for member records, disconnected tracking of daily activities, lack of geographical delegation across multiple municipal centres, and language barriers when tools lack proper Arabic RTL or French localization. Off-the-shelf software is often too complex, expensive, and unadapted to local governance structures.",
                solution: "A modern full-stack web application combining a React SPA frontend with a Laravel REST API. It features a tiered 4-role access hierarchy (Admin, Manager, Parent, Associate), a structured Algerian geographic database, a trilingual i18n engine (Arabic with native RTL, French, and English), dual-script member profiles (Arabic and Latin names), dynamic centre branding, and secure token-based authentication via Laravel Sanctum.",
                techSpec: [
                    { label: '4-Tier RBAC Architecture', detail: 'Granular role-based access control separating Super Admin (system-wide), Centre Manager (local facility), Parent (child overview), and Associate (daily operations) with dedicated dashboards.' },
                    { label: 'Algerian Geographic Hierarchy', detail: 'Normalized database mapping Wilaya → Commune → Etablissement (centre), enforcing strict jurisdictional boundaries on all operational queries.' },
                    { label: 'Trilingual i18n & RTL Engine', detail: 'Full native support for Arabic (with Right-to-Left RTL layout flipping), French, and English, seamlessly switching UI components and typography.' },
                    { label: 'Dual-Script Identity Management', detail: 'Database and form validation supporting both Arabic and Latin/French name fields to match official national civil registry standards.' },
                    { label: 'Dynamic Centre White-Labeling', detail: 'Customizable establishment settings (logo, association name, contact credentials) stored in MySQL and served dynamically to the frontend.' },
                    { label: 'Stateless API & Sanctum Auth', detail: 'Clean architectural decoupling with Laravel Sanctum token authentication, form request validation, and structured JSON API responses.' },
                ],
                tags: ['React 18', 'Vite', 'Laravel', 'Laravel Sanctum', 'MySQL', 'Ant Design', 'Tailwind CSS', 'RTL Engine', 'Geo Hierarchy', '4-Tier RBAC'],
            },
        ],
        ctaHeading: 'Want to build something like this?',
        ctaDesc: 'Check out the source code on GitHub or reach out to discuss system architecture.',
        ctaBtn: "Let's Talk",
        ctaBtnGithub: 'GitHub Profile',
    },
    about: {
        heroName: 'Merabet Ayache Zakaria',
        heroP1: 'I build modern websites and web applications that help businesses present themselves clearly, manage their work more efficiently, and turn ideas into digital products. My focus is on creating clean, practical, and user-friendly solutions for portfolios, company websites, management systems, registration platforms, and custom web apps.',
        heroP2: 'I work with React and Laravel, with an emphasis on usability, reliability, and solutions that create real value.',
        ctaBtn: 'Work With Me',
        cvBtn: 'Download CV',
        skillsLabel: 'Tech & Tools',
        skillsTitle: 'What I Work With',
        skillsSubtitle: 'The core technologies I use to deliver quality web applications.',
        skills: [
            {
                group: 'Frontend',
                items: ['HTML', 'CSS', 'JS', 'React', 'Antd', 'Responsive Design'],
            },
            {
                group: 'Backend',
                items: ['Laravel', 'MySQL', 'REST APIs', 'ORM', 'Authentication'],
            },
            {
                group: 'Tools',
                items: ['Git', 'GitHub', 'Axios'],
            },
            {
                group: 'Data Handling',
                items: ['CSV/PDF Export', 'Import'],
            },
        ],
        ctaHeading: "Let's build something together",
        ctaDesc: "Whether you need a product setup or a fully custom solution, I'm here to help.",
        ctaActionBtn: "Let's Talk"
    },
    contact: {
        label: 'Contact',
        heading: (
            <>
                Let's Build Something <span className="gradient-text">Together</span>
            </>
        ),
        desc: " Just pick your preferred way to reach me and let's talk about your project.",
        channels: {
            whatsapp: 'WhatsApp',
            whatsappDesc: 'Fastest way to reach me. Usually reply within a short time.',
            whatsappCta: 'Message on WhatsApp',
            phone: 'Phone',
            phoneDesc: 'I am available for calls .',
            phoneCta: 'Call Now',
            email: 'Email',
            emailDesc: 'For detailed project briefs or formal inquiries.',
            emailCta: 'Send an Email'
        },
        meta: {
            responseTime: 'Response Time',
            responseTimeVal: 'Within 24 hours',
            availability: 'Availability',
            availabilityVal: 'Remote · Worldwide'
        },
        form: {
            title: 'Send a Message',
            subtitle: 'Fill out the form below and I\'ll get back to you as soon as possible.',
            name: 'Full Name',
            namePlaceholder: 'John Doe',
            email: 'Email Address',
            emailPlaceholder: 'john@example.com',
            phone: 'Phone Number',
            phonePlaceholder: '+213 6XX XXX XXX',
            subject: 'Subject',
            subjectPlaceholder: 'Project inquiry',
            message: 'Message',
            messagePlaceholder: 'Tell me about your project, goals, and timeline...',
            send: 'Send Message',
            sending: 'Sending...',
            successTitle: 'Message Sent!',
            successDesc: 'Thank you for reaching out. I\'ll get back to you within 24 hours.',
            sendAnother: 'Send Another Message',
            errorTitle: 'Something went wrong',
            errorDesc: 'Please try again or reach out via one of the channels above.',
            retry: 'Try Again',
            validationRequired: 'This field is required',
            validationEmail: 'Please enter a valid email address',
            optional: 'Optional',
        }
    },
    footer: {
        brandDesc: 'Full-stack web developer. I design and build modern, custom websites and web applications that help businesses and individuals simplify their workflows and achieve their goals.',
        col1Title: 'Pages',
        col2Title: 'Services',
        col3Title: 'Connect',
        links: {
            services: 'Services',
            products: 'Products',
            work: 'Work',
            about: 'About',
            businessSites: 'Business Websites',
            webApps: 'Custom Web Apps',
            managementSystems: 'Management Systems',
            custom: 'Get a Quote',
            email: 'Email Me',
            downloadCv: 'Download CV'
        },
        rights: 'All rights reserved.'
    }
};
